apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: docs
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.40-192.168.1.49
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
